---

- name: "Deploy Salt master"
  hosts: all
  become: True
  become_user: root
  gather_facts: False

  tasks:

    - name: "Add saltstack repository"
      yum_repository:
        name: saltstack-repo
        description: EPEL YUM repo
        enabled: yes
        gpgcheck: yes
        gpgkey:
          - https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-GPG-KEY.pub
          - https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/base/RPM-GPG-KEY-CentOS-7
        baseurl: https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest

    - name: "Install SALT MASTER"
      yum:
        name: salt-master
        state: installed
        lock_timeout: 600

    - name: "Start SALT MASTER service"
      systemd:
        name: salt-master
        enabled: yes
        state: started

...
